esphome:
  name: esp-lamp
  friendly_name: esp-lamp

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_API_KEY"

ota:
  password: "YOUR_OTA_PASSWORD"

wifi: (YOUR_WIFI_CREDS)
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Lamp Fallback Hotspot"
    password: "YOUR_AP_PASSWORD"

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO3
    num_leds: 10
    name: "Light"
    id: esplamp
    effects:
      - random:
      - pulse:
          name: "Fast Pulse Max"
          transition_length: 0.2s
          update_interval: 0.2s
          min_brightness: 30%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse Min"
          transition_length: 0.2s
          update_interval: 0.2s
          min_brightness: 12%
          max_brightness: 30%

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true
    name: "Power"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - light.toggle: esplamp
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              message: Single
    - timing:
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at least 0.1s
      then:
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              message: Double
    - timing:
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at least 0.1s
      then:
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              message: Tripple
    - timing:
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for at most 1s
        - OFF for at least 0.1s
      then:
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              message: Quad
    - timing: 
        - ON for at least 2s
      then:
        - light.turn_on:
            id: esplamp
            brightness: 100%
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              message: Hold

sensor:
  - platform: rotary_encoder
    id: light_dimmer
    name: "Light Dimmer"
    pin_a:
      number: GPIO2
    pin_b:
      number: GPIO1
    min_value: 12
    max_value: 100
    resolution: 2
    internal: true
    filters:
      - debounce: 0.05s
    on_clockwise:
      then:
        - if:
            condition: 
              light.is_on: esplamp
            then:
              - if: 
                  condition:
                    lambda: 'return id(light_dimmer).state == 100;'
                  then:
                    - script.execute: brightness_warning_max
                  else:
                    - light.turn_on:
                        id: esplamp
                        brightness: !lambda |-
                          return (id(light_dimmer).state / 100.0);
                        transition_length: 200ms
                        
    on_anticlockwise:
      then:
        - if:
            condition: 
              light.is_on: esplamp
            then:
              - if: 
                  condition:
                    lambda: 'return id(light_dimmer).state == 12;'
                  then:
                    - script.execute: brightness_warning_min
                  else:
                    - light.turn_on:
                        id: esplamp
                        brightness: !lambda |-
                          return (id(light_dimmer).state / 100.0);
                        transition_length: 200ms

script:
  - id: brightness_warning_max
    then:
      - light.turn_on:
          id: esplamp
          effect: Fast Pulse Max
      - delay: 1s
      - light.turn_on:
          id: esplamp 
          effect: None
          brightness: 100%
  - id: brightness_warning_min
    then:
      - light.turn_on:
          id: esplamp
          effect: Fast Pulse Min
      - delay: 1s
      - light.turn_on:
          id: esplamp 
          effect: None 
          brightness: 12%
            
